basePath: /
definitions:
  internal_handler.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  internal_handler.LoginResponse:
    properties:
      token:
        type: string
    type: object
  internal_handler.MessageResponse:
    properties:
      message:
        type: string
    type: object
  internal_handler.RegisterRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Personal finance tracker & planner
  title: Finora WealthLab API
  version: "1.0"
paths:
  /:
    get:
      description: Returns API status
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Check server status
      tags:
      - health
  /api/login:
    post:
      consumes:
      - application/json
      description: Authenticate user and return JWT
      parameters:
      - description: login info
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/internal_handler.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_handler.LoginResponse'
      summary: Login user
      tags:
      - auth
  /api/register:
    post:
      consumes:
      - application/json
      description: Create new user
      parameters:
      - description: user info
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/internal_handler.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_handler.MessageResponse'
      summary: Register user
      tags:
      - auth
swagger: "2.0"
